
import java.awt.*;
import javax.swing.*;
import java.sql.*;
import java.util.Calendar;
import javax.swing.table.*;




/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Msyahrul Ar
 */
public class menu extends javax.swing.JFrame {
    /**
     * Creates new form menu
     */
    public menu() {
        initComponents();
        load_table();
        load_table1();
        tab1.setBackground(Color.white);
        jjam.setVisible(false);
        txtjam.setVisible(false);
        jcustom.setVisible(false);
        btncancel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grouppc = new javax.swing.ButtonGroup();
        grouppaket = new javax.swing.ButtonGroup();
        jPanel4 = new javax.swing.JPanel();
        tab1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tab2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tab3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tab4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jp1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        pc1 = new javax.swing.JRadioButton();
        pc2 = new javax.swing.JRadioButton();
        pc3 = new javax.swing.JRadioButton();
        pc4 = new javax.swing.JRadioButton();
        pc5 = new javax.swing.JRadioButton();
        txtpengguna = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        paket1 = new javax.swing.JRadioButton();
        paket3 = new javax.swing.JRadioButton();
        paket4 = new javax.swing.JRadioButton();
        paket2 = new javax.swing.JRadioButton();
        paket5 = new javax.swing.JRadioButton();
        paket6 = new javax.swing.JRadioButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        txtjam = new javax.swing.JTextField();
        jcustom = new javax.swing.JLabel();
        jjam = new javax.swing.JLabel();
        btncancel = new javax.swing.JButton();
        jp2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jview = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jview1 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jview2 = new javax.swing.JTable();
        btnview = new javax.swing.JButton();
        txtview = new javax.swing.JTextField();
        txtkol = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnselect = new javax.swing.JButton();
        btnselect1 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        txtmati = new javax.swing.JTextField();
        btnstop = new javax.swing.JButton();
        jp3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtnama = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtuser = new javax.swing.JTextField();
        txtpassw = new javax.swing.JTextField();
        txtreg = new javax.swing.JButton();
        txtres = new javax.swing.JButton();
        jp4 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(0, 102, 255));

        tab1.setBackground(new java.awt.Color(204, 204, 255));
        tab1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab1MouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel1.setText("BILING");

        javax.swing.GroupLayout tab1Layout = new javax.swing.GroupLayout(tab1);
        tab1.setLayout(tab1Layout);
        tab1Layout.setHorizontalGroup(
            tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tab1Layout.setVerticalGroup(
            tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        tab2.setBackground(new java.awt.Color(204, 204, 255));
        tab2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab2MouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel2.setText("DATA VIEW");

        javax.swing.GroupLayout tab2Layout = new javax.swing.GroupLayout(tab2);
        tab2.setLayout(tab2Layout);
        tab2Layout.setHorizontalGroup(
            tab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tab2Layout.setVerticalGroup(
            tab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        tab3.setBackground(new java.awt.Color(204, 204, 255));
        tab3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab3MouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel3.setText("REGISTRASI ADMIN");

        javax.swing.GroupLayout tab3Layout = new javax.swing.GroupLayout(tab3);
        tab3.setLayout(tab3Layout);
        tab3Layout.setHorizontalGroup(
            tab3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tab3Layout.setVerticalGroup(
            tab3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        tab4.setBackground(new java.awt.Color(204, 204, 255));
        tab4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab4MouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel4.setText("ABOUT");

        javax.swing.GroupLayout tab4Layout = new javax.swing.GroupLayout(tab4);
        tab4.setLayout(tab4Layout);
        tab4Layout.setHorizontalGroup(
            tab4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tab4Layout.setVerticalGroup(
            tab4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        jButton1.setBackground(new java.awt.Color(0, 102, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Log out");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/resources/img/logo-pure-white.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tab1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tab2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tab3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tab4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel29)
                            .addComponent(jLabel28)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel29)
                .addGap(25, 25, 25)
                .addComponent(jLabel28)
                .addGap(71, 71, 71)
                .addComponent(tab1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tab2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tab3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tab4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(34, 34, 34))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jPanel2.setPreferredSize(new java.awt.Dimension(638, 543));
        jPanel2.setLayout(new javax.swing.OverlayLayout(jPanel2));

        jp1.setBackground(new java.awt.Color(255, 255, 255));
        jp1.setPreferredSize(new java.awt.Dimension(638, 543));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel7.setText("BILING WARNET LINKERION");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("HARGA");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setText("PENGGUNA");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel13.setText("PC");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel14.setText("PAKET");

        pc1.setBackground(new java.awt.Color(255, 255, 255));
        grouppc.add(pc1);
        pc1.setText("PC1");

        grouppc.add(pc2);
        pc2.setText("PC2");

        grouppc.add(pc3);
        pc3.setText("PC3");

        grouppc.add(pc4);
        pc4.setText("PC4");

        grouppc.add(pc5);
        pc5.setText("PC5");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("5000/JAM");

        grouppaket.add(paket1);
        paket1.setText("PAKET A (1 JAM)");

        grouppaket.add(paket3);
        paket3.setText("PAKET C (3 JAM)");

        grouppaket.add(paket4);
        paket4.setText("PAKET D (4 JAM)");

        grouppaket.add(paket2);
        paket2.setText("PAKET B (2 JAM)");

        grouppaket.add(paket5);
        paket5.setText("PAKET E (5 JAM)");

        grouppaket.add(paket6);
        paket6.setText("PAKET (SPECIAL)");

        jButton2.setText("Submit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Custom");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jcustom.setText("Custom");

        jjam.setText("Jam");

        btncancel.setText("Cancel");
        btncancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jp1Layout = new javax.swing.GroupLayout(jp1);
        jp1.setLayout(jp1Layout);
        jp1Layout.setHorizontalGroup(
            jp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(192, 192, 192))
            .addGroup(jp1Layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addGroup(jp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12)
                    .addComponent(jLabel8)
                    .addGroup(jp1Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(70, 70, 70)
                        .addGroup(jp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtpengguna, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jp1Layout.createSequentialGroup()
                                .addComponent(pc1)
                                .addGap(18, 18, 18)
                                .addComponent(pc2)
                                .addGap(18, 18, 18)
                                .addComponent(pc3)
                                .addGap(18, 18, 18)
                                .addComponent(pc4)
                                .addGap(10, 10, 10)
                                .addComponent(pc5))
                            .addComponent(jLabel9)
                            .addGroup(jp1Layout.createSequentialGroup()
                                .addGroup(jp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jp1Layout.createSequentialGroup()
                                        .addComponent(paket1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(paket2))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jp1Layout.createSequentialGroup()
                                        .addComponent(paket3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                                        .addComponent(paket4)))
                                .addGroup(jp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jp1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton3))
                                    .addGroup(jp1Layout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addComponent(jcustom)
                                        .addGap(24, 24, 24)
                                        .addComponent(txtjam, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jjam))))
                            .addGroup(jp1Layout.createSequentialGroup()
                                .addGroup(jp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jp1Layout.createSequentialGroup()
                                        .addComponent(paket5)
                                        .addGap(19, 19, 19)
                                        .addComponent(paket6)))
                                .addGap(16, 16, 16)
                                .addComponent(btncancel)))))
                .addContainerGap(125, Short.MAX_VALUE))
        );
        jp1Layout.setVerticalGroup(
            jp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel7)
                .addGap(45, 45, 45)
                .addGroup(jp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pc1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(pc2)
                        .addComponent(pc3)
                        .addComponent(pc4)
                        .addComponent(pc5)
                        .addComponent(jLabel13)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                .addGroup(jp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtpengguna, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addGap(25, 25, 25)
                .addGroup(jp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(paket1)
                    .addComponent(paket2)
                    .addComponent(jLabel14)
                    .addComponent(jButton3))
                .addGroup(jp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(paket3)
                            .addComponent(paket4))
                        .addGap(18, 18, 18)
                        .addGroup(jp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(paket5)
                            .addComponent(paket6)))
                    .addGroup(jp1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtjam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcustom)
                            .addComponent(jjam))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btncancel)))
                .addGap(96, 96, 96)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92))
        );

        jPanel2.add(jp1);

        jp2.setBackground(new java.awt.Color(255, 255, 255));
        jp2.setPreferredSize(new java.awt.Dimension(638, 543));

        jview.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jview);

        jview1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Title 1"
            }
        ));
        jview1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jview1MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jview1);

        jview2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jview2);

        btnview.setText("Buat View");
        btnview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnviewActionPerformed(evt);
            }
        });

        jLabel10.setText("Nama View");

        jLabel11.setText("Isi Kolom");

        btnselect.setText("Select View");
        btnselect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnselectActionPerformed(evt);
            }
        });

        btnselect1.setText("Hapus");
        btnselect1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnselect1ActionPerformed(evt);
            }
        });

        jLabel15.setText("No Pc yang ingin dimatikan");

        btnstop.setText("Stop");
        btnstop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnstopActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jp2Layout = new javax.swing.GroupLayout(jp2);
        jp2.setLayout(jp2Layout);
        jp2Layout.setHorizontalGroup(
            jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jp2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4)
                    .addGroup(jp2Layout.createSequentialGroup()
                        .addGroup(jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnview, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jp2Layout.createSequentialGroup()
                                .addGroup(jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addGroup(jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel10)
                                        .addComponent(txtview)
                                        .addComponent(txtkol, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(btnselect, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnselect1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(111, Short.MAX_VALUE))
                    .addGroup(jp2Layout.createSequentialGroup()
                        .addComponent(txtmati, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnstop)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jp2Layout.setVerticalGroup(
            jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtmati, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnstop))
                .addGap(28, 28, 28)
                .addGroup(jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp2Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jp2Layout.createSequentialGroup()
                                .addComponent(txtview, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtkol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnselect, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnselect1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(27, 27, 27)
                        .addComponent(btnview, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel2.add(jp2);

        jp3.setBackground(new java.awt.Color(255, 255, 255));
        jp3.setPreferredSize(new java.awt.Dimension(638, 543));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel5.setText("REGISTRASI");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel16.setText("Nama");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel17.setText("Username");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel18.setText("Password");

        txtreg.setText("Register");
        txtreg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtregActionPerformed(evt);
            }
        });

        txtres.setText("Reset");
        txtres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jp3Layout = new javax.swing.GroupLayout(jp3);
        jp3.setLayout(jp3Layout);
        jp3Layout.setHorizontalGroup(
            jp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp3Layout.createSequentialGroup()
                .addGap(0, 191, Short.MAX_VALUE)
                .addGroup(jp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp3Layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addGap(300, 300, 300))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp3Layout.createSequentialGroup()
                            .addComponent(txtuser, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(138, 138, 138)))
                    .addGroup(jp3Layout.createSequentialGroup()
                        .addGroup(jp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17)
                            .addGroup(jp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtpassw, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 403, Short.MAX_VALUE)
                                .addComponent(txtnama, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtreg, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtres, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(250, 250, 250))
        );
        jp3Layout.setVerticalGroup(
            jp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp3Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtuser, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtpassw, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(jp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtreg, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtres, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(119, Short.MAX_VALUE))
        );

        jPanel2.add(jp3);

        jp4.setBackground(new java.awt.Color(255, 255, 255));
        jp4.setPreferredSize(new java.awt.Dimension(638, 543));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/resources/img/UNHASY.jpg"))); // NOI18N

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel19.setText("Aplikasi ini dibuat untuk memenuhi tugas dari Mahrus Ali S.Kom.,M.Pd.,M.Kom ");

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel21.setText("BASIS DATA LANJUT");

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel22.setText("Dirancang Oleh:");

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel23.setText("Muhammad Syahrul Anwar (1995114013)");

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel24.setText("Muhammad Nur Khakim      (1995114021)");

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/resources/img/1.png"))); // NOI18N

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/resources/img/2.png"))); // NOI18N

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/resources/img/3.png"))); // NOI18N

        javax.swing.GroupLayout jp4Layout = new javax.swing.GroupLayout(jp4);
        jp4.setLayout(jp4Layout);
        jp4Layout.setHorizontalGroup(
            jp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp4Layout.createSequentialGroup()
                .addContainerGap(143, Short.MAX_VALUE)
                .addGroup(jp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp4Layout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addGap(168, 168, 168)
                        .addComponent(jLabel26)
                        .addGap(159, 159, 159)
                        .addComponent(jLabel27)
                        .addGap(103, 103, 103))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp4Layout.createSequentialGroup()
                        .addGroup(jp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp4Layout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addGap(176, 176, 176))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp4Layout.createSequentialGroup()
                                .addGroup(jp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel23)
                                    .addComponent(jLabel24))
                                .addGap(118, 118, 118))
                            .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(125, 125, 125))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp4Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addGap(272, 272, 272))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp4Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addGap(230, 230, 230))))
        );
        jp4Layout.setVerticalGroup(
            jp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel20)
                .addGap(18, 18, 18)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jLabel22)
                .addGap(18, 18, 18)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(jp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel27)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48))
        );

        jPanel2.add(jp4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 732, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 556, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tab1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab1MouseClicked
    jp1.setVisible(true);
    jp2.setVisible(false);
    jp3.setVisible(false);
    jp4.setVisible(false);
    tab1.setBackground(Color.white);
    tab2.setBackground(new Color(204,204,255));
    tab3.setBackground(new Color(204,204,255));
    tab4.setBackground(new Color(204,204,255));
    }//GEN-LAST:event_tab1MouseClicked

    private void tab2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab2MouseClicked
    jp1.setVisible(false);
    jp2.setVisible(true);
    jp3.setVisible(false);
    jp4.setVisible(false);
    tab2.setBackground(Color.white);
    tab1.setBackground(new Color(204,204,255));
    tab3.setBackground(new Color(204,204,255));
    tab4.setBackground(new Color(204,204,255));
    }//GEN-LAST:event_tab2MouseClicked

    private void tab3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab3MouseClicked
    jp1.setVisible(false);
    jp2.setVisible(false);
    jp3.setVisible(true);
    jp4.setVisible(false);
    tab3.setBackground(Color.white);
    tab2.setBackground(new Color(204,204,255));
    tab1.setBackground(new Color(204,204,255));
    tab4.setBackground(new Color(204,204,255));
    }//GEN-LAST:event_tab3MouseClicked

    private void tab4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab4MouseClicked
    jp1.setVisible(false);
    jp2.setVisible(false);
    jp3.setVisible(false);
    jp4.setVisible(true);
    tab4.setBackground(Color.white);
    tab2.setBackground(new Color(204,204,255));
    tab3.setBackground(new Color(204,204,255));
    tab1.setBackground(new Color(204,204,255));
    }//GEN-LAST:event_tab4MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       bon();
       simpan();
       load_table();
       reset();
       
        jjam.setVisible(false);
        txtjam.setVisible(false);
        jcustom.setVisible(false);
        btncancel.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        reset2();
        
        
        jjam.setVisible(true);
        txtjam.setVisible(true);
        jcustom.setVisible(true);
        btncancel.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btncancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelActionPerformed
        jjam.setVisible(false);
        txtjam.setVisible(false);
        jcustom.setVisible(false);
        btncancel.setVisible(false);
    }//GEN-LAST:event_btncancelActionPerformed

    private void btnviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnviewActionPerformed
          try{
                Connection conn=new koneksi().getConnection();
                Statement stat= conn.createStatement();
                stat.executeUpdate("insert into daftar_view values ('"+txtview.getText()+"')"); 
        }catch (Exception e){   
    } 
          try{
                Connection conn=new koneksi().getConnection();
                Statement stat= conn.createStatement();
                stat.executeUpdate("create or replace view "+txtview.getText()+" as select * from data where pc = "+txtkol.getText()+"");   
            JOptionPane.showMessageDialog(null, "View terbuat");
        }catch (Exception e){     
    } 
          load_table1();
          reset3();
    }//GEN-LAST:event_btnviewActionPerformed

    private void jview1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jview1MouseClicked
        int baris = jview1.rowAtPoint(evt.getPoint());
        String nama = jview1.getValueAt(baris, 0).toString();
        txtview.setText(nama);
    }//GEN-LAST:event_jview1MouseClicked

    private void btnselectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnselectActionPerformed
        load_table2();
    }//GEN-LAST:event_btnselectActionPerformed

    private void btnselect1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnselect1ActionPerformed
          try{
              Connection conn=new koneksi().getConnection();
              Statement stat= conn.createStatement();
              stat.executeQuery ("drop view "+txtview.getText()+"");
              JOptionPane.showMessageDialog(this, "Berhasil di Hapus");
    }catch (Exception e){
              JOptionPane.showMessageDialog(this, e.getMessage());
    }
          try{
                Connection conn=new koneksi().getConnection();
                Statement stat= conn.createStatement();
                ResultSet set = stat.executeQuery("select * from daftar_view where nama='"+txtview.getText()+"'"); 
                
                if(set.next()){
                    if(txtview.getText().equals(set.getString("nama"))){
                    stat.executeUpdate("delete from daftar_view where nama ='"+txtview.getText()+"'");
                    }   
        }
        }catch (Exception e){   
    } 
          load_table1();
          reset3();
          new menu().setVisible(true);
          dispose();
    }//GEN-LAST:event_btnselect1ActionPerformed

    private void btnstopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnstopActionPerformed
        try{
                Connection conn=new koneksi().getConnection();
                Statement stat= conn.createStatement();
                ResultSet set = stat.executeQuery("select * from data where pc ='"+txtmati.getText()+"'"); 
                
                if(set.next()){
                    if(txtmati.getText().equals(set.getString("pc"))){
                    stat.executeUpdate("delete from data where pc ='"+txtmati.getText()+"'");
                    txtmati.setText("");
                    }
        }
                JOptionPane.showMessageDialog(null,"Pc berhasil dimatikan");
        }catch (Exception e){   
    } 
        load_table();
    }//GEN-LAST:event_btnstopActionPerformed

    private void txtresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtresActionPerformed
        txtuser.setText(null);
        txtnama.setText(null);
        txtpassw.setText(null);
    }//GEN-LAST:event_txtresActionPerformed

    private void txtregActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtregActionPerformed
        try{
            Connection conn=new koneksi().getConnection();
            Statement stat= conn.createStatement();
            stat.executeUpdate("INSERT INTO login VALUES('"
                +txtnama.getText()+"','"
                +txtuser.getText()+"','"
                +txtpassw.getText()+"')");
            JOptionPane.showMessageDialog(null, "Akun Berhasil Dibuat");
        }catch (Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        txtuser.setText(null);
        txtnama.setText(null);
        txtpassw.setText(null);
    }//GEN-LAST:event_txtregActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JOptionPane.showMessageDialog(null, "Berhasil Log out");
        new login().setVisible(true);
        dispose();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

     private void reset3(){
    txtview.setText(null);
    txtkol.setText(null);
     }
    
    private void reset2(){
    grouppaket.clearSelection();
    
}
    
    private void reset(){
    txtpengguna.setText(null);
    txtjam.setText(null);
    
    grouppc.clearSelection();
    grouppaket.clearSelection();
    
}
    private void bon(){
     int nopc;
        if(pc1.isSelected()){
            nopc=1;
        }else if(pc2.isSelected()){
            nopc=2;
        }else if(pc3.isSelected()){
            nopc=3;
        }else if(pc4.isSelected()){
            nopc=4;
        }else{
            nopc=5;
        }
        
    String durasi;
         if(paket1.isSelected()){
            durasi="1";
        }else if(paket2.isSelected()){
            durasi="2";
        }else if(paket3.isSelected()){
            durasi="3";
        }else if(paket4.isSelected()){
            durasi="4";
        }else if(paket5.isSelected()){
            durasi="5";
        }else if(paket6.isSelected()){
            durasi="6";
        }else{
            durasi=txtjam.getText();
        }
         
    int lamamain = Integer.parseInt(durasi);
    int jmlbayar = lamamain * 5000;
    
      //mebuat tampilan bon untuk mengetahui jumlah batar
      String output = "Data Pengguana : \n \n"
      +"Pengguna : "+txtpengguna.getText()+"\n"
      +"PC       : "+nopc+"\n"
      +"Pilihan Paket : "+durasi+"\n"
      +"Jumlah Bayar  : Rp "+jmlbayar+"\n"
              
      +"\n Uang pengguna : ";
      
      String bon = JOptionPane.showInputDialog(null,output, "Bon", JOptionPane.QUESTION_MESSAGE);
      int uangpengguna = Integer.parseInt(bon);
      int kembalian = uangpengguna - jmlbayar;
      JOptionPane.showMessageDialog(null, "Uang Kembalian = Rp" + kembalian);
    }
    
      private void simpan(){
      //mencari nomer pc dari radio button
      int nopc;
        if(pc1.isSelected()){
            nopc=1;
        }else if(pc2.isSelected()){
            nopc=2;
        }else if(pc3.isSelected()){
            nopc=3;
        }else if(pc4.isSelected()){
            nopc=4;
        }else{
            nopc=5;
        }
        
     // mencari nama paket dan durasi paket dari radio buton
    String namapaket;
    String durasi;
         if(paket1.isSelected()){
             namapaket="Paket A";
             durasi="1";
        }else if(paket2.isSelected()){
            namapaket="Paket B";
            durasi="2";
        }else if(paket3.isSelected()){
            namapaket="Paket C";
            durasi="3";
        }else if(paket4.isSelected()){
            namapaket="Paket D";
            durasi="4";
        }else if(paket5.isSelected()){
            namapaket="Paket E";
            durasi="5";
        }else if(paket6.isSelected()){
            namapaket="Paket F";
            durasi="6";
        }else{
            namapaket="Paket Custom";
            durasi=txtjam.getText();
        }
        
     // perhitungan jumlah bayar
    int lamamain = Integer.parseInt(durasi);
    int jmlbayar = lamamain * 5000;
    
    //mebuat tanggal dan waktu
    int detik, menit, jam, tanggal, bulan, tahun;
    Calendar date = Calendar.getInstance();
    detik = date.get(Calendar.SECOND);
    menit = date.get(Calendar.MINUTE);
    jam = date.get(Calendar.HOUR_OF_DAY);
    tanggal = date.get(Calendar.DAY_OF_MONTH);
    bulan = date.get(Calendar.MONTH);
    tahun = date.get(Calendar.YEAR);
    
    int selesai;
    if(jam+lamamain<24){
        selesai=jam+lamamain;
    }else{
        //perhitungan waktu jika melewati jam 12 malam
        int sisa = lamamain - (24-jam);
        selesai = sisa;
    }
    
            //menyimpan data yang telah diinput ke database
            try{
                Connection conn=new koneksi().getConnection();
                Statement stat= conn.createStatement();
                stat.executeUpdate("insert into data values('"
                        +nopc+"','"
                        +txtpengguna.getText()+"','"
                        +namapaket+"','"
                        +jmlbayar+"','"
                        +tanggal+"-"+(bulan+1)+"-"+tahun+"','"
                        +jam+":"+menit+":"+detik+"','"
                        +selesai+":"+menit+":"+detik+"')");       
            JOptionPane.showMessageDialog(null, "Data tersimpan");
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, "Data Gagal Input");     
    }  
 }
   //fungsi tabel 
   private void load_table() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("pc");
        model.addColumn("pengguna");
        model.addColumn("paket");
        model.addColumn("harga");
        model.addColumn("tanggal");
        model.addColumn("mulai");
        model.addColumn("selesai");
        try {
            int no=1;
            String sql = "select * from data";
            Connection conn=new koneksi().getConnection();
            Statement stat=conn.createStatement();
            ResultSet set=stat.executeQuery(sql);
            while(set.next()){
                model.addRow(new Object[]{set.getString(1),set.getString(2),set.getString(3),set.getString(4),set.getString(5),set.getString(6),set.getString(7)});
            }
         jview.setModel(model);
        }catch (Exception e){
    }
}
   //fungsi tabel view
    private void load_table1() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("nama");
        try {
            int no=1;
            String sql = "select * from daftar_view";
            Connection conn=new koneksi().getConnection();
            Statement stat=conn.createStatement();
            ResultSet set=stat.executeQuery(sql);
            while(set.next()){
                model.addRow(new Object[]{set.getString(1)});
            }
         jview1.setModel(model);
        }catch (Exception e){
    } 
}
    
       private void load_table2() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("pc");
        model.addColumn("pengguna");
        model.addColumn("paket");
        model.addColumn("harga");
        model.addColumn("tanggal");
        model.addColumn("mulai");
        model.addColumn("selesai");
        try {
            int no=1;
            String sql = "select * from ("+txtview.getText()+")";
            Connection conn=new koneksi().getConnection();
            Statement stat=conn.createStatement();
            ResultSet set=stat.executeQuery(sql);
            while(set.next()){
                model.addRow(new Object[]{set.getString(1),set.getString(2),set.getString(3),set.getString(4),set.getString(5),set.getString(6),set.getString(7)});
            }
            jview2.setModel(model);
        }catch (Exception e){
    }
}
   
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncancel;
    private javax.swing.JButton btnselect;
    private javax.swing.JButton btnselect1;
    private javax.swing.JButton btnstop;
    private javax.swing.JButton btnview;
    private javax.swing.ButtonGroup grouppaket;
    private javax.swing.ButtonGroup grouppc;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel jcustom;
    private javax.swing.JLabel jjam;
    private javax.swing.JPanel jp1;
    private javax.swing.JPanel jp2;
    private javax.swing.JPanel jp3;
    private javax.swing.JPanel jp4;
    private javax.swing.JTable jview;
    private javax.swing.JTable jview1;
    private javax.swing.JTable jview2;
    private javax.swing.JRadioButton paket1;
    private javax.swing.JRadioButton paket2;
    private javax.swing.JRadioButton paket3;
    private javax.swing.JRadioButton paket4;
    private javax.swing.JRadioButton paket5;
    private javax.swing.JRadioButton paket6;
    private javax.swing.JRadioButton pc1;
    private javax.swing.JRadioButton pc2;
    private javax.swing.JRadioButton pc3;
    private javax.swing.JRadioButton pc4;
    private javax.swing.JRadioButton pc5;
    private javax.swing.JPanel tab1;
    private javax.swing.JPanel tab2;
    private javax.swing.JPanel tab3;
    private javax.swing.JPanel tab4;
    private javax.swing.JTextField txtjam;
    private javax.swing.JTextField txtkol;
    private javax.swing.JTextField txtmati;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txtpassw;
    private javax.swing.JTextField txtpengguna;
    private javax.swing.JButton txtreg;
    private javax.swing.JButton txtres;
    private javax.swing.JTextField txtuser;
    private javax.swing.JTextField txtview;
    // End of variables declaration//GEN-END:variables
}
